<?php

namespace App\Helpers;

class MaterialIcons
{
    public static function getIcons(): array
    {
        return [
            // Production & Cinematic
            'movie' => 'movie',
            'videocam' => 'videocam',
            'movie_edit' => 'movie_edit',
            'video_library' => 'video_library',
            'theaters' => 'theaters',
            'camera_alt' => 'camera_alt',
            'camera' => 'camera',
            'photo_camera' => 'photo_camera',
            'mic' => 'mic',
            'mic_none' => 'mic_none',
            'volume_up' => 'volume_up',
            'sound_detection_dog_barking' => 'sound_detection_dog_barking',
            'tune' => 'tune',
            'auto_fix_high' => 'auto_fix_high',
            'palette' => 'palette',
            'closed_caption' => 'closed_caption',
            'subtitles' => 'subtitles',
            'play_arrow' => 'play_arrow',
            'pause' => 'pause',
            'stop' => 'stop',
            'skip_next' => 'skip_next',
            'skip_previous' => 'skip_previous',
            'slow_motion_video' => 'slow_motion_video',
            'repeat' => 'repeat',
            'shuffle' => 'shuffle',
            'featured_video' => 'featured_video',
            'missed_video_call' => 'missed_video_call',
            'video_call' => 'video_call',
            'video_settings' => 'video_settings',
            
            // Logistics & Operations
            'location_on' => 'location_on',
            'map' => 'map',
            'explore' => 'explore',
            'terrain' => 'terrain',
            'mountain' => 'mountain',
            'hiking' => 'hiking',
            'local_shipping' => 'local_shipping',
            'flight' => 'flight',
            'helicopter' => 'helicopter',
            'directions_bus' => 'directions_bus',
            'directions_car' => 'directions_car',
            'commute' => 'commute',
            'work' => 'work',
            'business_center' => 'business_center',
            'assignment' => 'assignment',
            'assignment_turned_in' => 'assignment_turned_in',
            'assignment_late' => 'assignment_late',
            'receipt' => 'receipt',
            'description' => 'description',
            'article' => 'article',
            'inventory' => 'inventory',
            'storage' => 'storage',
            'security' => 'security',
            'verified_user' => 'verified_user',
            'admin_panel_settings' => 'admin_panel_settings',
            'gavel' => 'gavel',
            'balance' => 'balance',
            'policy' => 'policy',
            'language' => 'language',
            'translate' => 'translate',
            'public' => 'public',
            'globe' => 'globe',

            // Communication & Support
            'phone' => 'phone',
            'call' => 'call',
            'mail' => 'mail',
            'email' => 'email',
            'chat' => 'chat',
            'forum' => 'forum',
            'contact_support' => 'contact_support',
            'help' => 'help',
            'info' => 'info',
            'feedback' => 'feedback',
            'live_help' => 'live_help',
            'person' => 'person',
            'groups' => 'groups',
            'handshake' => 'handshake',
            'support_agent' => 'support_agent',
            'headset_mic' => 'headset_mic',
            'share' => 'share',
            'thumbs_up' => 'thumbs_up',
            'recommend' => 'recommend',

            // Common UI actions
            'search' => 'search',
            'home' => 'home',
            'menu' => 'menu',
            'close' => 'close',
            'add' => 'add',
            'remove' => 'remove',
            'delete' => 'delete',
            'edit' => 'edit',
            'save' => 'save',
            'settings' => 'settings',
            'download' => 'download',
            'upload' => 'upload',
            'cloud_upload' => 'cloud_upload',
            'sync' => 'sync',
            'refresh' => 'refresh',
            'check' => 'check',
            'done' => 'done',
            'visibility' => 'visibility',
            'visibility_off' => 'visibility_off',
            'star' => 'star',
            'favorite' => 'favorite',
            'rocket_launch' => 'rocket_launch',
            'electric_bolt' => 'electric_bolt',
            'lightbulb' => 'lightbulb',
            'diamond' => 'diamond',
            'award_star' => 'award_star',
            'military_tech' => 'military_tech',
            'history' => 'history',
            'schedule' => 'schedule',
            'event' => 'event',
            'calendar_today' => 'calendar_today',
            'timer' => 'timer',
            'alarm' => 'alarm',

            // Specialized
            'agriculture' => 'agriculture',
            'construction' => 'construction',
            'engineering' => 'engineering',
            'architecture' => 'architecture',
            'medical_services' => 'medical_services',
            'emergency' => 'emergency',
            'health_and_safety' => 'health_and_safety',
            'science' => 'science',
            'biotech' => 'biotech',
            'school' => 'school',
            'diversity_3' => 'diversity_3',
            'volunteer_activism' => 'volunteer_activism',
            'eco' => 'eco',
            'forest' => 'forest',
            'water' => 'water',
            'energy_savings_leaf' => 'energy_savings_leaf',
        ];
    }
}
